// Code generated by goctl. DO NOT EDIT.
package types

type AppUser struct {
	Uid      int64  `json:"uid"`
	Auid     int64  `json:"auid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
	RefreshAfter int64  `json:"refresh_after,omitempty"`
}

type LoginAppUser struct {
	Uid      int64  `json:"uid"`
	Auid     int64  `json:"auid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
	JwtToken
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Type     int64  `json:"type"` //1.密码登陆，2.短信登陆
	Password string `json:"password"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"` //基本一个手机号码就完事
	Password string `json:"password"`
	Smscode  string `json:"smscode"` //短信码
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserReply struct {
	Auid     int64  `json:"auid"`
	Uid      int64  `json:"uid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
	JwtToken
}

type UserReq struct {
	Auid  int64 `json:"auid"`
	Uid   int64 `json:"uid"`
	Beid  int64 `json:"beid"`  //应用id
	Ptyid int64 `json:"ptyid"` //对应平台
}

type WxLoginReq struct {
	Beid  int64  `json:"beid"`  //应用id
	Code  string `json:"code"`  //微信登陆密钥
	Ptyid int64  `json:"ptyid"` //对应平台
}
