apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacenter_deploy
  namespace: datacenter_namespace
  labels:
    app: datacenter_deploy
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: datacenter_deploy
  template:
    metadata:
      labels:
        app: datacenter_deploy
    spec:
      containers:
      - name: datacenter_deploy
        image: datacenter_img
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: datacenter_deploy-svc
  namespace: datacenter_namespace
spec:
  ports:
    - port: 3000
  selector:
    app: datacenter_deploy

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: datacenter_deploy-hpa-c
  namespace: datacenter_namespace
  labels:
    app: datacenter_deploy-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datacenter_deploy
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: datacenter_deploy-hpa-m
  namespace: datacenter_namespace
  labels:
    app: datacenter_deploy-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datacenter_deploy
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
