// Code generated by goctl. DO NOT EDIT!
// Source: taizhang.proto

package server

import (
	"context"

	"datacenter/taizhang/rpc/internal/logic"
	"datacenter/taizhang/rpc/internal/svc"
	"datacenter/taizhang/rpc/taizhang"
)

type TaizhangServer struct {
	svcCtx *svc.ServiceContext
}

func NewTaizhangServer(svcCtx *svc.ServiceContext) *TaizhangServer {
	return &TaizhangServer{
		svcCtx: svcCtx,
	}
}

func (s *TaizhangServer) GetTaizhang(ctx context.Context, in *taizhang.TaizhangReq) (*taizhang.TaizhangResp, error) {
	l := logic.NewGetTaizhangLogic(ctx, s.svcCtx)
	return l.GetTaizhang(in)
}
