// Code generated by goctl. DO NOT EDIT!
// Source: taizhang.proto

//go:generate mockgen -destination ./taizhang_mock.go -package taizhangclient -source $GOFILE

package taizhangclient

import (
	"context"

	"datacenter/taizhang/rpc/taizhang"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	TaizhangReq  = taizhang.TaizhangReq
	TaizhangResp = taizhang.TaizhangResp

	Taizhang interface {
		GetTaizhang(ctx context.Context, in *TaizhangReq) (*TaizhangResp, error)
	}

	defaultTaizhang struct {
		cli zrpc.Client
	}
)

func NewTaizhang(cli zrpc.Client) Taizhang {
	return &defaultTaizhang{
		cli: cli,
	}
}

func (m *defaultTaizhang) GetTaizhang(ctx context.Context, in *TaizhangReq) (*TaizhangResp, error) {
	client := taizhang.NewTaizhangClient(m.cli.Conn())
	return client.GetTaizhang(ctx, in)
}
